---
- name: Update and Install Packages
  hosts: all
  become: yes
  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes
    - name: Upgrade existing packages
      apt:
        upgrade: yes
    - name: Install unzip package
      apt:
        name: unzip
        state: present