---
- name: Update and Install Packages
  hosts: localhost
  become: true
  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes
    - name: Upgrade existing packages
      apt:
        upgrade: yes
    - name: Create verification file
      file:
        path: /tmp/test.txt
        state: touch
    - name: Create additional verification file
      file:
        path: /tmp/test2.txt
        state: touch